import {
  Settings,
  LayoutDashboard,
  UtensilsCrossed,
  Phone,
  CalendarCheck,
  ChartSpline,
  BookOpen,
  FileText,
  Users,
  ShieldCheck,
  Building2,
  CreditCard,
  Bell,
  Rocket,
  MessageCircle,
  Zap,
  HelpCircle,
  Globe,
  Smartphone,
  BookMarked,
  BarChart2,
  Star,
  type LucideIcon,
  CircleQuestionMark,
  PhoneCall,
  MessageCircleHeart,
  ArrowDownToLine,
  MessagesSquare,
  Link,
  SquareUser,
  HatGlasses,
  HandCoins,
  Info,
  MessageSquareMore,
  NotebookPen,
  Ghost,
  CalendarCog,
  CalendarCheck2,
  UsersRound,
  Files,
  QrCode,
  ClockCheck,
  Image,
  Languages,
  ShieldAlert,
  ClipboardClock,
  UserPen,
  FileDown,
  ClipboardPen,
  FileX,
  BellElectric,
  BotMessageSquare,
  Images,
  ChartNetwork,
  FileChartColumn,
  MapPlus,
  BrickWallShield,
  FileCheck,
  FileUser,
  CalendarPlus,
  Calendars,
  Store,
  ShieldUser,
  PhoneOff,
  MessageSquareDot,
  PhoneForwarded,
  Bot,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Settings,
  LayoutDashboard,
  UtensilsCrossed,
  Phone,
  CalendarCheck,
  ChartSpline,
  BookOpen,
  FileText,
  Users,
  ShieldCheck,
  Building2,
  CreditCard,
  Bell,
  Rocket,
  MessageCircle,
  Zap,
  HelpCircle,
  Globe,
  Smartphone,
  BookMarked,
  BarChart2,
  Star,
  PhoneCall,
  MessageCircleHeart,
  ArrowDownToLine,
  MessagesSquare,
  Link,
  CircleQuestionMark,
  SquareUser,
  HatGlasses,
  HandCoins,
  Info,
  MessageSquareMore,
  NotebookPen,
  Ghost,
  CalendarCog,
  CalendarCheck2,
  UsersRound,
  Files,
  QrCode,
  ClockCheck,
  Image,
  Languages,
  ShieldAlert,
  ClipboardClock,
  UserPen,
  FileDown,
  ClipboardPen,
  BellElectric,
  FileX,
  BotMessageSquare,
  Images,
  ChartNetwork,
  FileChartColumn,
  MapPlus,
  BrickWallShield,
  FileCheck,
  FileUser,
  CalendarPlus,
  Calendars,
  Store,
  ShieldUser,
  PhoneOff,
  MessageSquareDot,
  PhoneForwarded,
  Bot,
  
};

export function getGuideIcon(name: string | undefined): LucideIcon {
  if (!name) return FileText;
  return iconMap[name] ?? FileText;
}

export function getDocSectionIcon(name: string | undefined): LucideIcon {
  if (!name) return BookMarked;
  return iconMap[name] ?? BookMarked;
}

export function getFaqIcon(name: string | undefined): LucideIcon {
  if (!name) return CircleQuestionMark
  return iconMap[name] ?? CircleQuestionMark
}